name: telegram message
on: [push, pull_request, issue_comment, pull_request_review, pull_request_review_comment]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@0.0.3
